#title: Würzburg Workshop on Next-Generation Communication Networks
email: wuewowas23@informatik.uni-wuerzburg.de
description: >- # this means to ignore newlines until "baseurl:"
  WueWoWAS'23 is a three-day workshop on next-generation communication networks. The goal of the workshop is to provide attendees with an opportunity to
  foster both their understanding of the current state of the art and to
  learn from experienced researchers in the field.

baseurl: "WueWoWas2023" # the subpath of your site, e.g. /blog

# Theme settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
#theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"


# Theme configuration
logo: "/assets/images/i3.png"

atom_feed:
  hide: true

plugins:
  - jekyll-feed
  - jekyll-include-cache

include: ["_pages"]

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: false
      read_time: true
      comments: false
      share: false
      related: false
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: false
      excerpt: "KuVS Fachgespräch - Würzburg Workshop on Next-Generation Communication Networks<br>28 - 30 June 2023"
      header:
        overlay_image: /assets/images/wue_header2.jpg
        actions:
          - label: "Call for Participation"
            url: "/cfp/"  

footer:
  links:
    - label: "Impressum"
      url: "/WueWoWas2023/impressum/"
